# User model representation for MongoDB
# This specifies the fields stored in the 'users' collection.

class UserDocument:
    """
    MongoDB 'users' collection schema description:
    
    - _id: ObjectId (generated by MongoDB)
    - email: str (unique)
    - password: str (hashed using pbkdf2_hmac)
    - full_name: str
    - role: str ("admin" | "compliance_officer" | "auditor")
    - created_at: str (ISO 8601 formatted datetime string)
    """
    pass
